#cloud-config
autoinstall:
  identity:
    hostname: laptop
    password: ubuntu
    realname: 'ubuntu'
    username: ubuntu
  keyboard:
    layout: us
    variant: ''
  late-commands:
  - 'echo "ubuntu ALL=(ALL) NOPASSWD: ALL" > /target/etc/sudoers.d/ubuntu'
  - chmod 440 /target/etc/sudoers.d/ubuntu
  - apt-get -y install linux-headers-$(uname -r)
  locale: en_US
  packages:
  - ubuntu-desktop
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: true
  version: 1
